(function initManicoApp(root){
  'use strict';
  const Core=root.ManicoCore,Store=root.ManicoStorage,Transcriber=root.ManicoTranscriber;
  if(!Core||!Store||!Transcriber)throw new Error('Manico modules missing');
  const $=id=>document.getElementById(id),audio=$('audio');
  const COPY={
    it:{product:'Bass Transcriber',import:'Importa audio',eyebrow:'Dal brano alle dita',heroTitle:'Ascolta. Trascrivi. Suona.',heroText:'Importa una registrazione, ricava la linea di basso e studiala sul manico. Audio, trascrizione e correzioni restano sul tuo dispositivo.',privacy:'Nessun upload. Tutto avviene nel browser.',dropTitle:'Porta qui il tuo brano',dropText:'MP3, WAV, M4A, AAC, OGG o FLAC',choose:'Scegli un file',yourTracks:'I tuoi brani',yourTracksHint:'Riapri una trascrizione e continua da dove eri rimasto.',examples:'Esercizi inclusi',examplesHint:'Linee essenziali pronte per provare il flusso.',empty:'Non hai ancora importato brani.',open:'Apri',remove:'Elimina',confirmDelete:'Eliminare questo brano e il suo audio?',notes:'note',storage:'Spazio locale',unavailable:'non disponibile',saved:'Salvato sul dispositivo',demo:'Esercizio incluso',previous:'precedente',current:'adesso',upcoming:'in arrivo',now:'Adesso',nextNotes:'Prossime note',study:'Studio',tuning:'Accordatura',frets:'Tasti',lookahead:'Note in anticipo',speed:'Velocità',loop:'Loop',setA:'Imposta A',setB:'Imposta B',clearLoop:'Azzera',noLoop:'nessun loop',correction:'Correggi la nota',semitoneDown:'− semitono',semitoneUp:'+ semitono',deleteNote:'Elimina nota',splitNote:'Dividi nota',export:'Esporta',exportTab:'Scarica TAB',exportProject:'Scarica progetto',confidence:'confidenza',string:'corda',fret:'tasto',notPlayable:'fuori manico',analyseTitle:'Trascrivi la linea di basso',analyseHint:'Il file resta sul dispositivo. La trascrizione è una stima e può essere corretta dopo l’importazione.',sensitivity:'Sensibilità agli attacchi',startAnalysis:'Trascrivi e salva',cancel:'Annulla',preparing:'Preparazione del segnale…',analysing:'Riconoscimento delle note…',decoding:'Decodifica dell’audio…',saving:'Salvataggio locale…',failed:'Non sono riuscito a trascrivere questo file.',noNotes:'Non ho trovato note affidabili. Prova con una sensibilità più alta o con un mix dove il basso è più presente.',persistentYes:'archiviazione persistente',persistentNo:'il browser può liberare spazio automaticamente',importedLine:'Linea di basso trascritta',keys:'Spazio: play/pausa · frecce: nota precedente/successiva',audioMissing:'L’audio salvato non è più disponibile, ma la trascrizione è rimasta.',version:`Versione ${Core.VERSION}`},
    en:{product:'Bass Transcriber',import:'Import audio',eyebrow:'From the track to your fingers',heroTitle:'Listen. Transcribe. Play.',heroText:'Import a recording, extract the bass line and practise it on the fretboard. Audio, transcription and corrections stay on your device.',privacy:'No upload. Everything happens in your browser.',dropTitle:'Drop your track here',dropText:'MP3, WAV, M4A, AAC, OGG or FLAC',choose:'Choose a file',yourTracks:'Your tracks',yourTracksHint:'Reopen a transcription and continue where you left off.',examples:'Included exercises',examplesHint:'Essential lines ready to demonstrate the workflow.',empty:'You have not imported a track yet.',open:'Open',remove:'Delete',confirmDelete:'Delete this track and its stored audio?',notes:'notes',storage:'Local storage',unavailable:'unavailable',saved:'Saved on device',demo:'Included exercise',previous:'previous',current:'now',upcoming:'coming next',now:'Now',nextNotes:'Next notes',study:'Practice',tuning:'Tuning',frets:'Frets',lookahead:'Look-ahead notes',speed:'Speed',loop:'Loop',setA:'Set A',setB:'Set B',clearLoop:'Clear',noLoop:'no loop',correction:'Correct note',semitoneDown:'− semitone',semitoneUp:'+ semitone',deleteNote:'Delete note',splitNote:'Split note',export:'Export',exportTab:'Download TAB',exportProject:'Download project',confidence:'confidence',string:'string',fret:'fret',notPlayable:'outside fretboard',analyseTitle:'Transcribe the bass line',analyseHint:'The file stays on your device. The transcription is an estimate and can be corrected after import.',sensitivity:'Attack sensitivity',startAnalysis:'Transcribe and save',cancel:'Cancel',preparing:'Preparing the signal…',analysing:'Recognising notes…',decoding:'Decoding audio…',saving:'Saving locally…',failed:'This file could not be transcribed.',noNotes:'No reliable notes were found. Try a higher sensitivity or a mix with a more prominent bass.',persistentYes:'persistent storage',persistentNo:'the browser may reclaim storage automatically',importedLine:'Transcribed bass line',keys:'Space: play/pause · arrows: previous/next note',audioMissing:'The stored audio is no longer available, but the transcription remains.',version:`Version ${Core.VERSION}`}
  };
  const state={lang:'it',tracks:[],track:null,currentIndex:0,pendingFile:null,cancelled:false,audioUrl:null,playing:false,animation:0,demoTimer:0,demoClock:0,saveTimer:0,persistent:false,synth:null};
  const t=key=>COPY[state.lang][key]??key;
  function readLanguage(){try{const saved=localStorage.getItem('manico-language');if(saved==='en'||saved==='it')return saved;}catch(error){}return(navigator.language||'').toLowerCase().startsWith('en')?'en':'it';}
  function applyLanguage(){document.documentElement.lang=state.lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const value=t(el.dataset.i18n);if(value!==undefined)el.textContent=value;});$('langIt').classList.toggle('on',state.lang==='it');$('langEn').classList.toggle('on',state.lang==='en');$('versionLabel').textContent=t('version');renderHome();if(state.track)renderStudio(true);}
  function setLanguage(lang){state.lang=lang;try{localStorage.setItem('manico-language',lang);}catch(error){}applyLanguage();}
  function show(view){$('homeView').hidden=view!=='home';$('studioView').hidden=view!=='studio';}
  function bytes(value){if(!value)return'0 MB';const units=['B','KB','MB','GB'];let amount=value,index=0;while(amount>=1024&&index<units.length-1){amount/=1024;index++;}return`${amount.toFixed(index>1?1:0)} ${units[index]}`;}
  async function refreshStorage(){const estimate=await Store.estimate(),suffix=state.persistent?t('persistentYes'):t('persistentNo');$('storageLabel').textContent=estimate.quota?`${t('storage')}: ${bytes(estimate.usage)} / ${bytes(estimate.quota)} · ${suffix}`:`${t('storage')}: ${t('unavailable')} · ${suffix}`;}
  function stringName(index){const tuning=Core.TUNINGS[state.track?.settings?.tuning||'4'];return tuning&&index!==null?Core.noteName(tuning.open[index]).replace(/-?\d+$/,''):'?';}
  function safeName(value){return String(value||'bass-line').trim().replace(/[^a-z0-9._-]+/gi,'-').replace(/^-+|-+$/g,'')||'bass-line';}
  function download(name,text,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);}
  function trackCard(track){const article=document.createElement('article');article.className='track-card';const cover=document.createElement('div');cover.className='cover';cover.textContent=track.demo?track.style.slice(0,2).toUpperCase():'MP3';const info=document.createElement('div'),title=document.createElement('h3'),meta=document.createElement('div');title.textContent=track.title;meta.className='meta';meta.textContent=`${track.events?.length||0} ${t('notes')} · ${Core.formatTime(track.duration)}${track.demo?` · ${track.style}`:''}`;info.append(title,meta);const actions=document.createElement('div');actions.className='card-actions';const open=document.createElement('button');open.className='icon-button';open.textContent='▶';open.title=t('open');open.onclick=()=>openTrack(track.id,!!track.demo);actions.append(open);if(!track.demo){const remove=document.createElement('button');remove.className='icon-button danger';remove.textContent='×';remove.title=t('remove');remove.onclick=async event=>{event.stopPropagation();if(!confirm(t('confirmDelete')))return;await Store.remove(track.id);await loadLibrary();await refreshStorage();};actions.append(remove);}article.append(cover,info,actions);return article;}
  function renderHome(){const list=$('trackList');if(!list)return;list.replaceChildren();if(!state.tracks.length){const empty=document.createElement('div');empty.className='empty-card';empty.textContent=t('empty');list.append(empty);}else state.tracks.forEach(track=>list.append(trackCard(track)));const demos=$('demoList');demos.replaceChildren();Core.DEMOS.forEach(def=>demos.append(trackCard(Core.createDemoTrack(def))));}
  async function loadLibrary(){state.tracks=await Store.list();renderHome();}
  function stopAudio(){cancelAnimationFrame(state.animation);clearTimeout(state.demoTimer);audio.pause();audio.removeAttribute('src');audio.load();if(state.audioUrl)URL.revokeObjectURL(state.audioUrl);state.audioUrl=null;state.playing=false;}
  function ensureSettings(){state.track.settings={tuning:'4',frets:15,lookahead:3,speed:1,loopA:null,loopB:null,...(state.track.settings||{})};const tuning=Core.TUNINGS[state.track.settings.tuning]||Core.TUNINGS['4'];state.track.events=Core.optimiseFingering(state.track.events||[],tuning.open,state.track.settings.frets);}
  async function openTrack(id,demo=false){stopAudio();const track=demo?Core.createDemoTrack(Core.DEMOS.find(item=>item.id===id)||Core.DEMOS[0]):await Store.get(id);if(!track)return;state.track=track;state.currentIndex=0;state.demoClock=0;ensureSettings();if(track.audioBlob){state.audioUrl=URL.createObjectURL(track.audioBlob);audio.src=state.audioUrl;audio.preload='metadata';audio.playbackRate=track.settings.speed||1;}show('studio');renderStudio(true);startAnimation();}
  function scheduleSave(){if(!state.track||state.track.demo)return;clearTimeout(state.saveTimer);state.saveTimer=setTimeout(async()=>{state.track.updatedAt=Date.now();await Store.save(state.track);$('savedLabel').textContent=t('saved');await loadLibrary();},420);}
  function currentTime(){return state.track?.demo?state.demoClock:(audio.currentTime||0);}
  function setTime(value){if(!state.track)return;const time=Core.clamp(value,0,state.track.duration||0);if(state.track.demo){state.demoClock=time;state.currentIndex=Core.currentEventIndex(state.track.events,time,state.currentIndex);if(state.playing)scheduleDemo();}else audio.currentTime=time;updatePlayback(true);}
  function selected(){return state.track?.events?.[state.currentIndex]||null;}
  function selectEvent(index,seek=true){if(!state.track?.events?.length)return;state.currentIndex=Core.clamp(index,0,state.track.events.length-1);if(seek)setTime(state.track.events[state.currentIndex].start);renderStudio(true);}
  function renderTimeline(){const box=$('phraseStrip');box.replaceChildren();const events=state.track.events,start=Math.max(0,state.currentIndex-7),end=Math.min(events.length,state.currentIndex+22),ahead=state.track.settings.lookahead;for(let i=start;i<end;i++){const event=events[i],button=document.createElement('button');button.className=`phrase-note${i===state.currentIndex?' current':i>state.currentIndex&&i<=state.currentIndex+ahead?' next':''}`;const strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=Core.noteName(event.midi);small.textContent=`${Core.formatTime(event.start)} · ${event.string===null?'—':`${stringName(event.string)}${event.fret}`}`;button.append(strong,small);button.onclick=()=>selectEvent(i);box.append(button);}requestAnimationFrame(()=>box.querySelector('.current')?.scrollIntoView({inline:'center',block:'nearest',behavior:'smooth'}));}
  function renderFretboard(){const svg=$('fretboard'),track=state.track,tuning=Core.TUNINGS[track.settings.tuning],open=tuning.open,strings=open.length,frets=track.settings.frets,W=1200,H=Math.max(330,78+strings*62),nut=105,right=1164,top=43,row=strings>1?(H-104)/(strings-1):0,fx=f=>nut+Core.fretPosition(f,frets)*(right-nut),cx=f=>f===0?nut-31:(fx(f-1)+fx(f))/2,order=[...open.keys()].reverse();svg.setAttribute('viewBox',`0 0 ${W} ${H}`);let html='<defs><linearGradient id="wood" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="var(--wood1)"/><stop offset="1" stop-color="var(--wood2)"/></linearGradient></defs>';html+=`<rect x="${nut}" y="20" width="${right-nut}" height="${H-62}" rx="12" fill="url(#wood)"/><rect x="${nut-7}" y="20" width="7" height="${H-62}" fill="var(--nut)" opacity=".92"/>`;for(let f=1;f<=frets;f++)html+=`<line x1="${fx(f)}" y1="20" x2="${fx(f)}" y2="${H-42}" stroke="var(--fretwire)" stroke-width="${f<5?4:3}" opacity=".8"/>`;order.forEach((string,r)=>{const y=top+r*row;html+=`<line x1="55" y1="${y}" x2="${right}" y2="${y}" stroke="var(--string)" stroke-width="${1.35+(open.length-string)*.6}" opacity=".72"/><text x="18" y="${y+7}" fill="var(--muted)" font-size="22" font-family="var(--mono)">${stringName(string)}</text>`;});[3,5,7,9,12,15,17,19,21,24].filter(f=>f<=frets).forEach(f=>{const x=cx(f),y=top+row*(strings-1)/2;if(f%12===0)html+=`<circle cx="${x}" cy="${y-25}" r="7" fill="var(--inlay)"/><circle cx="${x}" cy="${y+25}" r="7" fill="var(--inlay)"/>`;else html+=`<circle cx="${x}" cy="${y}" r="7" fill="var(--inlay)"/>`;});for(let f=0;f<=frets;f++)html+=`<text x="${cx(f)}" y="${H-10}" text-anchor="middle" fill="var(--faint)" font-size="15" font-family="var(--mono)">${f}</text>`;const markers=[];if(state.currentIndex>0)markers.push({event:track.events[state.currentIndex-1],kind:'past',order:''});if(selected())markers.push({event:selected(),kind:'current',order:''});for(let n=1;n<=track.settings.lookahead;n++){const event=track.events[state.currentIndex+n];if(event)markers.push({event,kind:'next',order:String(n)});}markers.forEach(marker=>{const event=marker.event;if(event.string===null||event.fret===null)return;const r=order.indexOf(event.string);if(r<0||event.fret>frets)return;const x=cx(event.fret),y=top+r*row,current=marker.kind==='current',past=marker.kind==='past',opacity=marker.kind==='next'?Math.max(.28,1-Number(marker.order)*.18):1,radius=current?30:23,color=past?'var(--past)':current?'var(--accent)':'var(--future)';html+=`<g opacity="${opacity}"><circle cx="${x}" cy="${y}" r="${radius}" fill="${past?'none':color}" stroke="${color}" stroke-width="${past?4:2}"/><text x="${x}" y="${y+6}" text-anchor="middle" font-size="${current?18:15}" font-weight="900" fill="${current?'#211608':past?'var(--past)':'#10201b'}">${marker.order||Core.noteName(event.midi)}</text></g>`;});svg.innerHTML=html;}
  function renderSide(){const event=selected();$('nowNote').textContent=event?Core.noteName(event.midi):'—';$('nowPosition').textContent=event&&event.string!==null?`${t('string')} ${stringName(event.string)} · ${t('fret')} ${event.fret}`:t('notPlayable');$('confidenceLabel').textContent=event?`${t('confidence')} ${Math.round((event.confidence||0)*100)}%`:'';const list=$('nextList');list.replaceChildren();for(let n=1;n<=state.track.settings.lookahead;n++){const event=state.track.events[state.currentIndex+n];if(!event)continue;const row=document.createElement('div');row.className='next-row';const order=document.createElement('span');order.className='order';order.textContent=n;const name=document.createElement('b');name.textContent=Core.noteName(event.midi);const pos=document.createElement('span');pos.textContent=event.string===null?'—':`${stringName(event.string)}${event.fret}`;row.append(order,name,pos);list.append(row);}$('noteSelect').value=event?String(event.midi):'';$('noteDown').disabled=!event;$('noteUp').disabled=!event;$('deleteNote').disabled=!event||state.track.events.length<=1;$('splitNote').disabled=!event||event.end-event.start<.12;}
  function renderLoop(){const{loopA,loopB}=state.track.settings;$('loopLabel').textContent=loopA!==null&&loopB!==null?`A ${Core.formatTime(loopA)} — B ${Core.formatTime(loopB)}`:t('noLoop');}
  function renderStudio(full=false){if(!state.track)return;$('trackTitle').value=state.track.title;$('trackMeta').textContent=`${state.track.demo?t('demo'):t('importedLine')} · ${state.track.events.length} ${t('notes')} · ${Core.TUNINGS[state.track.settings.tuning].label}`;$('savedLabel').textContent=state.track.demo?t('demo'):t('saved');$('tuningSelect').value=state.track.settings.tuning;$('fretsSelect').value=String(state.track.settings.frets);$('lookaheadSelect').value=String(state.track.settings.lookahead);$('speedSelect').value=String(state.track.settings.speed);$('playButton').textContent=state.playing?'❚❚':'▶';renderTimeline();renderFretboard();renderSide();renderLoop();if(full)updatePlayback(false);}
  function updatePlayback(force=false){if(!state.track)return;const time=currentTime(),duration=state.track.duration||audio.duration||0;$('seek').value=duration?time/duration*1000:0;$('clock').textContent=`${Core.formatTime(time)} / ${Core.formatTime(duration)}`;const index=Core.currentEventIndex(state.track.events,time,state.currentIndex);if(index!==state.currentIndex||force){state.currentIndex=index;renderTimeline();renderFretboard();renderSide();}}
  function startAnimation(){cancelAnimationFrame(state.animation);const frame=()=>{if(!state.track)return;const{loopA,loopB}=state.track.settings;if(state.playing&&loopA!==null&&loopB!==null&&currentTime()>=loopB)setTime(loopA);updatePlayback(false);state.animation=requestAnimationFrame(frame);};frame();}
  function pluck(midi,duration=.5){state.synth||=new(window.AudioContext||window.webkitAudioContext)();if(state.synth.state==='suspended')state.synth.resume();const now=state.synth.currentTime,f=440*Math.pow(2,(midi-69)/12),osc=state.synth.createOscillator(),gain=state.synth.createGain(),filter=state.synth.createBiquadFilter();osc.type='triangle';osc.frequency.value=f;filter.type='lowpass';filter.frequency.setValueAtTime(1200,now);filter.frequency.exponentialRampToValueAtTime(260,now+duration);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.28,now+.01);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.connect(filter);filter.connect(gain);gain.connect(state.synth.destination);osc.start(now);osc.stop(now+duration+.04);}
  function scheduleDemo(){clearTimeout(state.demoTimer);if(!state.playing||!state.track?.demo)return;const event=selected();if(!event)return;state.demoClock=event.start;pluck(event.midi,Math.min(.8,(event.end-event.start)/state.track.settings.speed));state.demoTimer=setTimeout(()=>{if(!state.playing)return;if(state.currentIndex>=state.track.events.length-1){state.playing=false;state.currentIndex=0;state.demoClock=0;renderStudio(true);return;}state.currentIndex++;state.demoClock=state.track.events[state.currentIndex].start;renderStudio(true);scheduleDemo();},Math.max(90,(event.end-event.start)*1000/state.track.settings.speed));}
  async function togglePlay(){if(!state.track)return;state.playing=!state.playing;if(state.track.demo){if(state.playing)scheduleDemo();else clearTimeout(state.demoTimer);}else if(state.track.audioBlob){try{audio.playbackRate=state.track.settings.speed;if(state.playing)await audio.play();else audio.pause();}catch(error){state.playing=false;}}else{state.playing=false;alert(t('audioMissing'));}renderStudio(false);}
  function recalc(){const tuning=Core.TUNINGS[state.track.settings.tuning];state.track.events=Core.optimiseFingering(state.track.events,tuning.open,state.track.settings.frets);scheduleSave();renderStudio(true);}
  function changeMidi(value,absolute=false){const event=selected();if(!event)return;event.midi=Core.clamp(absolute?Number(value):event.midi+value,23,76);event.confidence=1;recalc();}
  function deleteCurrent(){if(!state.track||state.track.events.length<=1)return;state.track.events.splice(state.currentIndex,1);state.currentIndex=Core.clamp(state.currentIndex,0,state.track.events.length-1);recalc();}
  function splitCurrent(){const event=selected();if(!event||event.end-event.start<.12)return;const middle=(event.start+event.end)/2,second={...event,id:`${event.id}-b-${Date.now()}`,start:middle};event.end=middle;state.track.events.splice(state.currentIndex+1,0,second);recalc();}
  function setLoop(which){const time=currentTime();if(which==='A')state.track.settings.loopA=Math.min(time,state.track.settings.loopB??time);else state.track.settings.loopB=Math.max(time,state.track.settings.loopA??0);if(state.track.settings.loopA!==null&&state.track.settings.loopB!==null&&state.track.settings.loopB-state.track.settings.loopA<.15)state.track.settings.loopB=Math.min(state.track.duration,state.track.settings.loopA+.15);scheduleSave();renderLoop();}
  function clearLoop(){state.track.settings.loopA=null;state.track.settings.loopB=null;scheduleSave();renderLoop();}
  function exportProject(){const track=state.track,project={manico:5,version:Core.VERSION,title:track.title,duration:track.duration,settings:track.settings,events:track.events.map(event=>({start:event.start,end:event.end,midi:event.midi,note:Core.noteName(event.midi),confidence:event.confidence,string:event.string,fret:event.fret}))};download(`${safeName(track.title)}.manico.json`,JSON.stringify(project,null,2),'application/json');}
  function openImport(file){if(!file)return;state.pendingFile=file;state.cancelled=false;$('importFileName').textContent=file.name;$('analysisStatus').textContent=t('analyseHint');$('analysisProgress').style.width='0%';$('startAnalysis').disabled=false;$('analysisModal').hidden=false;}
  async function startImport(){const file=state.pendingFile;if(!file)return;state.cancelled=false;$('startAnalysis').disabled=true;try{$('analysisStatus').textContent=t('decoding');$('analysisProgress').style.width='4%';const buffer=await Transcriber.decode(file);if(state.cancelled)return;const events=await Transcriber.transcribe(buffer,{sensitivity:Number($('sensitivity').value)/100,onProgress(value,stage){$('analysisProgress').style.width=`${Math.round(value*100)}%`;$('analysisStatus').textContent=stage==='prepare'?t('preparing'):t('analysing');}});if(state.cancelled)return;if(!events.length)throw new Error('NO_NOTES');$('analysisStatus').textContent=t('saving');const id=`track-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,now=Date.now(),settings={tuning:'4',frets:15,lookahead:3,speed:1,loopA:null,loopB:null},track={id,title:file.name.replace(/\.[^.]+$/,''),filename:file.name,mime:file.type,audioBlob:file,duration:buffer.duration,createdAt:now,updatedAt:now,settings,events:Core.optimiseFingering(events,Core.TUNINGS['4'].open,15)};await Store.save(track);$('analysisModal').hidden=true;await loadLibrary();await refreshStorage();await openTrack(id,false);}catch(error){$('startAnalysis').disabled=false;$('analysisProgress').style.width='0%';$('analysisStatus').textContent=error?.message==='NO_NOTES'?t('noNotes'):t('failed');}}
  function cancelImport(){state.cancelled=true;state.pendingFile=null;$('analysisModal').hidden=true;}
  function populate(){ $('tuningSelect').innerHTML=Object.entries(Core.TUNINGS).map(([key,item])=>`<option value="${key}">${item.label}</option>`).join('');$('fretsSelect').innerHTML=[12,15,18,24].map(value=>`<option value="${value}">${value}</option>`).join('');$('lookaheadSelect').innerHTML=[2,3,4,5].map(value=>`<option value="${value}">${value}</option>`).join('');$('speedSelect').innerHTML=[.5,.65,.75,.85,1,1.1,1.25].map(value=>`<option value="${value}">${Math.round(value*100)}%</option>`).join('');$('noteSelect').innerHTML=Array.from({length:54},(_,i)=>23+i).map(midi=>`<option value="${midi}">${Core.noteName(midi)}</option>`).join(''); }
  function bind(){ $('langIt').onclick=()=>{state.lang='it';try{localStorage.setItem('manico-language','it');}catch(error){}applyLanguage();};$('langEn').onclick=()=>{state.lang='en';try{localStorage.setItem('manico-language','en');}catch(error){}applyLanguage();};$('homeButton').onclick=()=>{stopAudio();state.track=null;show('home');};$('importTop').onclick=()=>$('fileInput').click();$('chooseFile').onclick=()=>$('fileInput').click();$('fileInput').onchange=()=>{openImport($('fileInput').files[0]);$('fileInput').value='';};$('startAnalysis').onclick=startImport;$('cancelAnalysis').onclick=cancelImport;$('sensitivity').oninput=event=>$('sensitivityValue').textContent=`${event.target.value}%`;const drop=$('dropzone');drop.ondragover=event=>{event.preventDefault();drop.classList.add('over');};drop.ondragleave=()=>drop.classList.remove('over');drop.ondrop=event=>{event.preventDefault();drop.classList.remove('over');openImport(event.dataTransfer.files[0]);};$('backHome').onclick=()=>{stopAudio();state.track=null;show('home');};$('playButton').onclick=togglePlay;$('seek').oninput=event=>setTime(Number(event.target.value)/1000*(state.track?.duration||0));$('speedSelect').onchange=event=>{state.track.settings.speed=Number(event.target.value);audio.playbackRate=state.track.settings.speed;scheduleSave();if(state.playing&&state.track.demo)scheduleDemo();};$('tuningSelect').onchange=event=>{state.track.settings.tuning=event.target.value;recalc();};$('fretsSelect').onchange=event=>{state.track.settings.frets=Number(event.target.value);recalc();};$('lookaheadSelect').onchange=event=>{state.track.settings.lookahead=Number(event.target.value);scheduleSave();renderStudio(true);};$('setLoopA').onclick=()=>setLoop('A');$('setLoopB').onclick=()=>setLoop('B');$('clearLoop').onclick=clearLoop;$('noteSelect').onchange=event=>changeMidi(Number(event.target.value),true);$('noteDown').onclick=()=>changeMidi(-1);$('noteUp').onclick=()=>changeMidi(1);$('deleteNote').onclick=deleteCurrent;$('splitNote').onclick=splitCurrent;$('exportTab').onclick=()=>download(`${safeName(state.track.title)}.txt`,Core.renderTab(state.track,state.track.settings.tuning));$('exportProject').onclick=exportProject;$('trackTitle').onchange=event=>{state.track.title=event.target.value.trim()||state.track.title;scheduleSave();};audio.onplay=()=>{state.playing=true;renderStudio(false);};audio.onpause=()=>{state.playing=false;renderStudio(false);};audio.onended=()=>{state.playing=false;setTime(0);renderStudio(false);};audio.onloadedmetadata=()=>{if(state.track&&!state.track.duration)state.track.duration=audio.duration;updatePlayback(true);};document.addEventListener('keydown',event=>{if(['INPUT','SELECT','TEXTAREA'].includes(event.target.tagName)||$('studioView').hidden)return;if(event.code==='Space'){event.preventDefault();togglePlay();}else if(event.key==='ArrowRight')selectEvent(state.currentIndex+1);else if(event.key==='ArrowLeft')selectEvent(state.currentIndex-1);}); }
  async function init(){state.lang=readLanguage();populate();bind();state.persistent=await Store.persist();await loadLibrary();await refreshStorage();applyLanguage();show('home');}
  init().catch(error=>{$('fatalError').hidden=false;$('fatalError').textContent=error?.message||String(error);console.error(error);});
})(globalThis);
