(function initManicoTranscriber(root){
  'use strict';
  const Core=root.ManicoCore;const TARGET_RATE=5512;
  function source(){return `'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function percentile(values,ratio){if(!values.length)return 0;const sorted=values.slice().sort((a,b)=>a-b);return sorted[Math.max(0,Math.min(sorted.length-1,Math.floor((sorted.length-1)*ratio)))];}
function rms(signal,start,length){let sum=0,end=Math.min(signal.length,start+length);for(let i=start;i<end;i++){const v=signal[i];sum+=v*v;}return Math.sqrt(sum/Math.max(1,end-start));}
function onsets(signal,sr,sensitivity){const hop=Math.max(1,Math.round(sr*.012)),win=Math.max(hop*3,Math.round(sr*.045)),energy=[];for(let p=0;p+win<signal.length;p+=hop)energy.push(rms(signal,p,win));const noise=percentile(energy,.32),strong=percentile(energy,.9),threshold=noise+(strong-noise)*(1-sensitivity)*.72,flux=energy.map((v,i)=>i<2?0:v-Math.max(energy[i-1],energy[i-2])),fluxThreshold=Math.max(.000003,percentile(flux.filter(v=>v>0),.67)*(1.08-sensitivity*.35)),gap=Math.max(1,Math.round(.065*sr/hop)),out=[];let last=-gap;for(let i=2;i<energy.length-2;i++){const local=energy[i]>=energy[i-1]&&energy[i]>=energy[i+1];if(local&&energy[i]>threshold&&flux[i]>fluxThreshold&&i-last>=gap){out.push(i*hop/sr);last=i;}}if(!out.length||out[0]>.18)out.unshift(0);return out;}
function corr(signal,start,size,lag){let xy=0,xx=0,yy=0,end=Math.min(signal.length,start+size-lag);for(let i=start;i<end;i++){const a=signal[i],b=signal[i+lag];xy+=a*b;xx+=a*a;yy+=b*b;}return xy/(Math.sqrt(xx*yy)||1);}
function pitch(signal,sr,time){const votes=[];for(const offset of [.028,.078,.132]){const start=Math.max(0,Math.floor((time+offset)*sr)),size=Math.min(Math.round(sr*.16),signal.length-start);if(size<Math.round(sr*.08))continue;const minLag=Math.max(2,Math.floor(sr/330)),maxLag=Math.min(Math.floor(sr/31),Math.floor(size/2));let bestLag=-1,best=-1;const scores=new Float32Array(maxLag+1);for(let lag=minLag;lag<=maxLag;lag++){const score=corr(signal,start,size,lag);scores[lag]=score;if(score>best){best=score;bestLag=lag;}}if(bestLag<0||best<.48)continue;if(bestLag*2<=maxLag&&scores[bestLag*2]>best*.88)bestLag*=2;const midi=Math.round(69+12*Math.log2((sr/bestLag)/440));if(midi>=23&&midi<=64)votes.push({midi,confidence:best});}if(!votes.length)return null;const grouped=new Map();for(const vote of votes){const item=grouped.get(vote.midi)||{score:0,count:0};item.score+=vote.confidence;item.count++;grouped.set(vote.midi,item);}let selected=null;for(const [midi,item]of grouped){const score=item.score+item.count*.15;if(!selected||score>selected.score)selected={midi,score,confidence:item.score/item.count};}return selected;}
function smooth(events){if(events.length<2)return events;const candidates=events.map(event=>[...new Set([event.midi,event.midi-12,event.midi+12].filter(m=>m>=23&&m<=64))]),costs=[],back=[];candidates.forEach((list,i)=>{costs[i]=new Array(list.length).fill(Infinity);back[i]=new Array(list.length).fill(-1);list.forEach((m,j)=>{const octave=Math.abs(m-events[i].midi)*.11;if(i===0){costs[i][j]=octave;return;}candidates[i-1].forEach((pm,k)=>{const jump=Math.abs(m-pm),large=jump>12?(jump-12)*.45:0,value=costs[i-1][k]+jump*.16+large+octave;if(value<costs[i][j]){costs[i][j]=value;back[i][j]=k;}});});});let cursor=0,last=costs.at(-1);last.forEach((v,i)=>{if(v<last[cursor])cursor=i;});for(let i=events.length-1;i>=0;i--){events[i].midi=candidates[i][cursor];cursor=back[i][cursor];if(cursor<0&&i>0)cursor=0;}return events;}
self.onmessage=event=>{const{signal,sampleRate,sensitivity,duration}=event.data,points=onsets(signal,sampleRate,sensitivity),events=[];for(let i=0;i<points.length;i++){const start=points[i],next=i+1<points.length?points[i+1]:Math.min(duration,start+.7),found=pitch(signal,sampleRate,start);if(found&&found.confidence>=.48)events.push({start,end:Math.max(start+.06,next),midi:found.midi,confidence:clamp(found.confidence,0,1)});if(i%6===0)self.postMessage({type:'progress',value:(i+1)/points.length});}smooth(events);const compact=[];for(const item of events){const previous=compact.at(-1);if(previous&&previous.midi===item.midi&&item.start-previous.end<.035){previous.end=item.end;previous.confidence=Math.max(previous.confidence,item.confidence);}else compact.push(item);}self.postMessage({type:'result',events:compact});};`;}
  function worker(){const url=URL.createObjectURL(new Blob([source()],{type:'text/javascript'})),instance=new Worker(url);instance.__url=url;return instance;}
  async function decode(file){const context=new (window.AudioContext||window.webkitAudioContext)();try{return await context.decodeAudioData((await file.arrayBuffer()).slice(0));}finally{await context.close();}}
  async function prepare(buffer,onProgress=()=>{}){const ratio=buffer.sampleRate/TARGET_RATE,length=Math.max(1,Math.floor(buffer.length/ratio)),output=new Float32Array(length),channels=Array.from({length:buffer.numberOfChannels},(_,i)=>buffer.getChannelData(i)),dt=1/buffer.sampleRate,hpRC=1/(2*Math.PI*30),hpAlpha=hpRC/(hpRC+dt),lpAlpha=1-Math.exp(-2*Math.PI*360/buffer.sampleRate);let hp=0,previous=0,lp=0;const chunk=180000;for(let start=0;start<length;start+=chunk){const end=Math.min(length,start+chunk);for(let out=start;out<end;out++){const s0=Math.floor(out*ratio),s1=Math.max(s0+1,Math.floor((out+1)*ratio));let sum=0,count=0;for(let s=s0;s<s1&&s<buffer.length;s++){let sample=0;for(const channel of channels)sample+=channel[s]||0;sample/=channels.length;hp=hpAlpha*(hp+sample-previous);previous=sample;lp+=lpAlpha*(hp-lp);sum+=lp;count++;}output[out]=count?sum/count:0;}onProgress(end/length);await new Promise(resolve=>setTimeout(resolve,0));}return{signal:output,sampleRate:TARGET_RATE};}
  async function transcribe(buffer,options={}){const progress=options.onProgress||(()=>{}),prepared=await prepare(buffer,value=>progress(value*.22,'prepare')),instance=worker();return new Promise((resolve,reject)=>{instance.onmessage=event=>{if(event.data.type==='progress'){progress(.22+event.data.value*.78,'analyse');return;}if(event.data.type==='result'){instance.terminate();URL.revokeObjectURL(instance.__url);resolve(Core.normalizeEvents(event.data.events,buffer.duration));}};instance.onerror=error=>{instance.terminate();URL.revokeObjectURL(instance.__url);reject(error);};instance.postMessage({signal:prepared.signal,sampleRate:prepared.sampleRate,sensitivity:Number.isFinite(options.sensitivity)?options.sensitivity:.72,duration:buffer.duration},[prepared.signal.buffer]);});}
  root.ManicoTranscriber={decode,transcribe};
})(globalThis);
